services:
  cmd_vel_publisher:
    image: canvas:${CANVAS_VERSION:-latest}
    env_file: .env
    volumes:
      - ./config:/workspace/src/canvas/agent/cmd_vel_publisher/config
    working_dir: /workspace/src/canvas/agent/cmd_vel_publisher
    command: /bin/bash -c "source /opt/ros/jazzy/setup.bash && python3 cmd_vel_publisher.py --config config/segway_e1.yml"
    network_mode: "host"
    ipc: host
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  neural_planner:
    image: canvas:${CANVAS_VERSION:-latest}
    env_file: .env
    volumes:
      - ./config:/workspace/src/canvas/agent/neural_planner/config
      - ./maps:/workspace/src/canvas/agent/neural_planner/maps
    working_dir: /workspace/src/canvas/agent/neural_planner
    command: /bin/bash -c "source /opt/ros/jazzy/setup.bash && python3 neural_planner.py --config config/config.yml"
    network_mode: "host"
    ipc: host
    tty: true
