#!/usr/bin/env bash
# Setup pre-commit hooks with support for both devcontainer and local environments

set -e

echo "Setting up pre-commit hooks..."

# Detect the correct Python interpreter
if [ -x "/isaac-sim/kit/python/bin/python3" ]; then
    PYTHON_CMD="/isaac-sim/kit/python/bin/python3"
    echo "Detected Isaac Sim Python (devcontainer environment)"
elif command -v python3 > /dev/null; then
    PYTHON_CMD="python3"
    echo "Using system python3"
else
    echo "Error: python3 not found"
    exit 1
fi

# Install pre-commit hooks
echo "Installing pre-commit hooks using: $PYTHON_CMD"
$PYTHON_CMD -m pre_commit install

# Update the pre-commit hook to support both environments
HOOK_FILE=".git/hooks/pre-commit"

if [ -f "$HOOK_FILE" ]; then
    echo "Updating pre-commit hook to support both devcontainer and local environments..."

    # Create a temporary file with the updated hook
    cat > "$HOOK_FILE.tmp" << 'EOF'
#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03

# start templated
INSTALL_PYTHON=/usr/bin/python3
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
# end templated

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

# Try to find the correct Python interpreter with pre-commit installed
# Priority order:
# 1. Isaac Sim Python (devcontainer)
# 2. Python in PATH with pre-commit module
# 3. Original INSTALL_PYTHON
# 4. pre-commit command in PATH

if [ -x "/isaac-sim/kit/python/bin/python3" ] && /isaac-sim/kit/python/bin/python3 -m pre_commit --version > /dev/null 2>&1; then
    exec /isaac-sim/kit/python/bin/python3 -mpre_commit "${ARGS[@]}"
elif command -v python3 > /dev/null && python3 -m pre_commit --version > /dev/null 2>&1; then
    exec python3 -mpre_commit "${ARGS[@]}"
elif [ -x "$INSTALL_PYTHON" ] && "$INSTALL_PYTHON" -m pre_commit --version > /dev/null 2>&1; then
    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
elif command -v pre-commit > /dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
EOF

    # Replace the hook file
    mv "$HOOK_FILE.tmp" "$HOOK_FILE"
    chmod +x "$HOOK_FILE"

    echo "✓ Pre-commit hook updated successfully"
else
    echo "Warning: Pre-commit hook file not found at $HOOK_FILE"
    exit 1
fi

echo ""
echo "✓ Pre-commit hooks setup complete!"
echo ""
echo "The hooks will now run automatically on git commit."
echo "To run hooks manually on all files: $PYTHON_CMD -m pre_commit run --all-files"
